### ISSUE TITLE
vscode: cannot access built in declaration.

### ISSUE THREAD

**Issue by Abhinav1217** [fwcd/kotlin-language-server#153] opened 2019-08-26 15:02 UTC
I am starting to learn kotlin language and decided to use vscode instead of IntellJ IDEA to better learn stuff by doing things manually.

On the very first variable program, Code is showing me following error:
```
Cannot access built-in declaration 'kotlin.String'. Ensure that you have a dependency on the Kotlin standard librarykotlin(MISSING_BUILT_IN_DECLARATION)
```
However the code is actually not wrong. I can compile it and run it without any issue. 
```
fun main() {
    val name: String = "Abhinav001"
    println(name)
}
```
Terminal :
```
abhinav@abhinav-sol ~/Projects/kotlin-lang $ kotlinc Variable.kt 
abhinav@abhinav-sol ~/Projects/kotlin-lang $ kotlin VariableKt
Abhinav001
```
 I even tried importing `kotlin.String` on top but still language-server is showing errors, despite code being correct. 

Am I missing some configuration step for kotlin-language-server? I do not want to use IntellJ IDE for learning kotlin.

**Comment by fwcd** [comment] 2019-08-26 16:05
You need either a Gradle or Maven project currently. Try using [kotlin-quick-start](https://github.com/fwcd/kotlin-quick-start) (instead of `kotlinc` you have to run `./gradlew build` or `./gradlew run`).

**Comment by fwcd** [comment] 2019-08-26 16:30
Closing as a duplicate of #95.

**Closed by fwcd** 2019-08-26 16:30 UTC
Labels: dependency resolution

**Comment by Abhinav1217** [comment] 2019-08-27 04:08
So the language server is currently focusing on professional environment only? Not on simple scripting or simple code learning? :sob: 

In #95 you have recently merged a fix. So does this mean it will support in future release? Or It can be resolved now by setting KOTLIN_HOME manually?

**Comment by Abhinav1217** [comment] 2019-08-27 04:44
A funny discovery, 

Since code itself is not erroneous I thought using kotlin-quick-start to create a project which the language-server can use to lint my code, and still use `kotlinc` to compile and run single files.  Many thanks for that by the way. I never used gradle before.

Turns out as soon as I installed gradle, using `sdk install gradle`, language-server suddenly started functioning as expected. Without adding a gradle project in the directory.  

Maybe its just me? or maybe it automatically finds gradle libs. In any case, gradle is a dependency of this language-server to work on single files. Haven;t tried with maven yet.

**Comment by fwcd** [comment] 2019-08-27 13:05
That is correct, the next release should be able to find `kotlinc`'s standard library without having to install Gradle or Maven. The language server previously just searched in the local Gradle repository, which is why it worked for you after installing Gradle (and presumably opening kotlin-quick-start or any other project which depends on Kotlin‘s stdlib and thus downloads it).

**Comment by mustaqimM** [comment] 2020-10-17 03:32
@fwcd Is there anything more that needs to be done? I'm running it from Emacs without Gradle and I still get this error. `kotlinc` is in my path along with its libraries:
```
/usr/bin/kotlin
/usr/bin/kotlinc
/usr/bin/kotlinc-js
/usr/bin/kotlinc-jvm
/usr/share/kotlin-bin/build.txt
/usr/share/kotlin-bin/lib/allopen-compiler-plugin.jar
/usr/share/kotlin-bin/lib/android-extensions-compiler.jar
/usr/share/kotlin-bin/lib/android-extensions-runtime.jar
/usr/share/kotlin-bin/lib/annotations-13.0.jar
/usr/share/kotlin-bin/lib/js.engines.jar
/usr/share/kotlin-bin/lib/jvm-abi-gen.jar
/usr/share/kotlin-bin/lib/kotlin-annotation-processing-cli.jar
/usr/share/kotlin-bin/lib/kotlin-annotation-processing-runtime.jar
/usr/share/kotlin-bin/lib/kotlin-annotation-processing.jar
/usr/share/kotlin-bin/lib/kotlin-annotations-android.jar
/usr/share/kotlin-bin/lib/kotlin-annotations-jvm-sources.jar
/usr/share/kotlin-bin/lib/kotlin-annotations-jvm.jar
/usr/share/kotlin-bin/lib/kotlin-ant.jar
/usr/share/kotlin-bin/lib/kotlin-compiler.jar
/usr/share/kotlin-bin/lib/kotlin-coroutines-experimental-compat-sources.jar
/usr/share/kotlin-bin/lib/kotlin-coroutines-experimental-compat.jar
/usr/share/kotlin-bin/lib/kotlin-daemon-client.jar
/usr/share/kotlin-bin/lib/kotlin-daemon.jar
/usr/share/kotlin-bin/lib/kotlin-imports-dumper-compiler-plugin.jar
/usr/share/kotlin-bin/lib/kotlin-main-kts.jar
/usr/share/kotlin-bin/lib/kotlin-preloader.jar
/usr/share/kotlin-bin/lib/kotlin-reflect-sources.jar
/usr/share/kotlin-bin/lib/kotlin-reflect.jar
/usr/share/kotlin-bin/lib/kotlin-runner.jar
/usr/share/kotlin-bin/lib/kotlin-script-runtime-sources.jar
/usr/share/kotlin-bin/lib/kotlin-script-runtime.jar
/usr/share/kotlin-bin/lib/kotlin-scripting-common.jar
/usr/share/kotlin-bin/lib/kotlin-scripting-compiler-impl.jar
/usr/share/kotlin-bin/lib/kotlin-scripting-compiler.jar
/usr/share/kotlin-bin/lib/kotlin-scripting-js.jar
/usr/share/kotlin-bin/lib/kotlin-scripting-jvm.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib-jdk7-sources.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib-jdk7.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib-jdk8-sources.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib-jdk8.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib-js-sources.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib-js.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib-sources.jar
/usr/share/kotlin-bin/lib/kotlin-stdlib.jar
/usr/share/kotlin-bin/lib/kotlin-test-js-sources.jar
/usr/share/kotlin-bin/lib/kotlin-test-js.jar
/usr/share/kotlin-bin/lib/kotlin-test-junit-sources.jar
/usr/share/kotlin-bin/lib/kotlin-test-junit.jar
/usr/share/kotlin-bin/lib/kotlin-test-junit5-sources.jar
/usr/share/kotlin-bin/lib/kotlin-test-junit5.jar
/usr/share/kotlin-bin/lib/kotlin-test-sources.jar
/usr/share/kotlin-bin/lib/kotlin-test-testng-sources.jar
/usr/share/kotlin-bin/lib/kotlin-test-testng.jar
/usr/share/kotlin-bin/lib/kotlin-test.jar
/usr/share/kotlin-bin/lib/kotlinx-coroutines-core.jar
/usr/share/kotlin-bin/lib/kotlinx-serialization-compiler-plugin.jar
/usr/share/kotlin-bin/lib/mutability-annotations-compat.jar
/usr/share/kotlin-bin/lib/noarg-compiler-plugin.jar
/usr/share/kotlin-bin/lib/sam-with-receiver-compiler-plugin.jar
/usr/share/kotlin-bin/lib/trove4j.jar
```
