### ISSUE TITLE
Go-to-definition does not work after go-to-definition on an external source

### ISSUE THREAD

**Issue by aiguofer** [fwcd/kotlin-language-server#470] opened 2023-05-14 02:39 UTC
I'll preface this saying I'm using Emacs and I'm not sure if this is an issue with KLS or with lsp-mode on Emacs, or some missbehavior between the two.

The Emacs lsp-mode offers a way to configure `useKlsScheme`. It defaults to true, and it says it's recommended, but this doesn't seem to work when I try to go-to-def: `The following file kls:file:///Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home/lib/src.zip!/java.sql/javax/sql/DataSource.java?source=true is missing, ignoring from the results.`

When I turn this off, go-to-def works by making some sort of temp file of the (jar extracted) decompiled class or source in `/var`. When it opens the file, it tries to load the file as a standalone script instead of knowing it was part of the project I navigated from. This means I can't go-to-def from that file since it does not have a classpath.

**Comment by RenanKummer** [comment] 2023-09-20 22:45
The same issue is happening in VS Code as well. Go-to-definition is not working for anything really, not even standard library stuff such as `mapOf` or `Pair`.

**Comment by fwcd** [comment] 2023-10-03 18:58
Thanks for reporting this, I've found the issue and it seems to actually be a regression introduced with the class path cache in #337. Precisely the issue is here:

https://github.com/fwcd/kotlin-language-server/blob/8f96c293caf6dd040539d33e05a5d26f427a4a70/shared/src/main/kotlin/org/javacs/kt/classpath/CachedClassPathResolver.kt#L72

Notice how we call `.toString()` on a nullable value (`it.sourceJar` of type `Path?`): This means absent source jars would have been stored as the string `"null"` in the database, rather than `null` as the schema would suggest:

https://github.com/fwcd/kotlin-language-server/blob/8f96c293caf6dd040539d33e05a5d26f427a4a70/shared/src/main/kotlin/org/javacs/kt/classpath/CachedClassPathResolver.kt#L24

This then in turn caused

https://github.com/fwcd/kotlin-language-server/blob/8f96c293caf6dd040539d33e05a5d26f427a4a70/server/src/main/kotlin/org/javacs/kt/externalsources/ClassPathSourceArchiveProvider.kt#L6-L11

to return bogus results (paths containing the string `"null"`), which then led to an equally invalid `resolvedUri` in `ClassContentProvider`:

https://github.com/fwcd/kotlin-language-server/blob/8f96c293caf6dd040539d33e05a5d26f427a4a70/server/src/main/kotlin/org/javacs/kt/externalsources/ClassContentProvider.kt#L38

Unfortunately, the database schema has now shipped, so we'll actually have to introduce some form of versioning to make sure user databases are rebuilt after fixing this (I've opened #503 for that, PR for the actual fix is underway...).

cc @daplf

**Comment by daplf** [comment] 2023-10-03 21:42
Apologies for the regression :/

Opened a PR to add database versioning: https://github.com/fwcd/kotlin-language-server/pull/504

Once that one is merged, I can also make a PR to fix the actual issue.

**Comment by fwcd** [comment] 2023-10-03 23:35
Oh, no worries, that stuff happens. Thanks for the quick response, I'll have a look at #504!

We should probably add a few more tests for definition lookups on external libraries that cover all of the common cases (JDK, JAR with source, JAR without source, ...) to make sure that we don't regress on this in the future.

**Closed** 2023-10-04 10:57 UTC
Labels: bug
