### ISSUE TITLE
VSCode Couldn't Start Language Client, Internal Error

### ISSUE THREAD

**Issue by win93** [fwcd/kotlin-language-server#220] opened 2020-07-09 04:29 UTC
When using this extension in a project where the project directory contains spaces, I get this stack trace and cannot use the extension without renaming the path the project resides in:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 26: file:///Users/example/path containing spaces/project
	at java.net.URI.create(URI.java:852)
	at org.javacs.kt.util.URIsKt.parseURI(URIs.kt:14)
	at org.javacs.kt.KotlinLanguageServer.initialize(KotlinLanguageServer.kt:73)
	... 16 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 26: file:///Users/example/path containing spaces/project
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 18 more
```

Extension version: 0.2.18
Platform: macOS 10.15.5
kotlinc version: 1.3.72 (JRE 1.8.0_191-b12)

**Comment by fwcd** [comment] 2020-07-09 10:13
Duplicate of https://github.com/fwcd/kotlin-language-server/issues/200, which was fixed in https://github.com/fwcd/kotlin-language-server/pull/204. The fix hasn't been deployed to a release yet, however.

For now, you could either remove the space in your folder name, wait for the next KLS release or build KLS yourself.

**Closed by fwcd** 2020-07-09 10:13 UTC
