### ISSUE TITLE
Support for kotlin multiplatform

### ISSUE THREAD

**Issue by kangwang1988** [fwcd/kotlin-language-server#448] opened 2023-04-06 23:45 UTC
<img width="1083" alt="Screenshot 2023-04-07 at 07 41 10" src="https://user-images.githubusercontent.com/817851/230512970-bf5caa0c-baf1-4cc7-a552-26d793d484b8.png">

It seems that the language server didn't regard the symbols defined in jsmain/jvmmain as two symbols.
Besides, there is something error reported in the build.gradle.kts
<img width="891" alt="Screenshot 2023-04-07 at 07 42 59" src="https://user-images.githubusercontent.com/817851/230513116-b562beda-e39e-4d50-b06a-8f25619eb3bf.png">

**Comment by themkat** [comment] 2023-04-07 06:42
Kotlin Language Server currently only have VERY experimental support for Kotlin Multiplatform projects. I think part of the problem here is that none of the current contributors have much experience in Multiplatform projects (my only experience is fixing the minimal multiplatform support for JVM). If you, or anyone else, wants to contribute and dive deeper into implementing multiplatform support, that would be awesome 😄

**Comment by fwcd** [comment] 2023-04-14 16:52
Duplicate of #11

**Closed by fwcd** 2023-04-14 16:52 UTC
Labels: enhancement
